{
 "title": "Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "route", "label": "Route", "query": { "query": "label_values(http_route)" } },
   {
    "name": "status",
    "label": "Status",
    "query": {
     "query": "label_values(http_response_status_code)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(service_instance_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Request Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Rate by Route",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_route) (rate({__name__=~\"http_server_request_duration(_seconds)?_count\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors (Client Side)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_response_status_code, http_route) (rate({__name__=~\"http_server_request_duration(_seconds)?_count\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors (Server Side)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_response_status_code, http_route) (rate({__name__=~\"http_server_request_duration(_seconds)?_count\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Request/Response Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Average Request Body Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"http_server_request_body_size(_bytes)?_sum\"}[5m])) by (http_route) / sum(rate({__name__=~\"http_server_request_body_size(_bytes)?_count\"}[5m])) by (http_route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Body Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"http_server_response_body_size(_bytes)?_sum\"}[5m])) by (http_route) / sum(rate({__name__=~\"http_server_response_body_size(_bytes)?_count\"}[5m])) by (http_route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Total Bytes In (Request)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (http_route) (rate({__name__=~\"http_server_request_body_size(_bytes)?_sum\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Total Bytes Out (Response)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (http_route) (rate({__name__=~\"http_server_response_body_size(_bytes)?_sum\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Request Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"http_server_request_duration(_seconds)?_sum\"}[5m])) by (http_route)/sum(rate({__name__=~\"http_server_request_duration(_seconds)?_count\"}[5m])) by (http_route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration (p95 Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate({__name__=~\"http_server_request_duration(_seconds)?_bucket\"}[5m])) by (le, http_route))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration (p99 Latency)",
   "type": "timeseries",
   "description": "Shows the 99th percentile latency over time.\nGrouped by HTTP route.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate({__name__=~\"http_server_request_duration(_seconds)?_bucket\"}[5m])) by (le, http_route))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}