{{ if .Values.developer.enabled  }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cs-store
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/resource-policy": keep
spec:
  storageClassName: {{ .Values.global.storageClassName }}
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: {{ .Values.developer.localCSPath }}
---
{{ end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cs-store
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/resource-policy": keep
spec:
{{ if .Values.developer.enabled  }}
  volumeName: pv-cs-store
{{ end }}
  storageClassName: {{ .Values.global.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
