{{- if kindIs "map" .Values.diracx.osDbs.default }}
{{- if and (hasKey .Values.diracx.osDbs.default "ca.crt") (hasKey .Values.diracx.osDbs.default "tls.crt") (hasKey .Values.diracx.osDbs.default "tls.key") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: os-certs-default
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: kubernetes.io/tls
data:
  ca.crt: {{ index .Values.diracx.osDbs.default "ca.crt" | b64enc | quote }}
  tls.crt: {{ index .Values.diracx.osDbs.default "tls.crt" | b64enc | quote }}
  tls.key: {{ index .Values.diracx.osDbs.default "tls.key" | b64enc | quote }}
{{- end }}

{{- range $dbName, $dbConfig := .Values.diracx.osDbs.dbs }}
{{- if kindIs "map" $dbConfig }}
{{- if and (hasKey $dbConfig "ca.crt") (hasKey $dbConfig "tls.crt") (hasKey $dbConfig "tls.key") }}
{{- $osCaCrt := index $dbConfig "ca.crt" | toString | trim }}
{{- $osTlsCrt := index $dbConfig "tls.crt" | toString | trim }}
{{- $osTlsKey := index $dbConfig "tls.key" | toString | trim }}
{{- $safeDbName := $dbName | lower | replace "_" "-" | replace "." "-" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "os-certs-%s" $safeDbName | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: kubernetes.io/tls
data:
  ca.crt: {{ $osCaCrt | b64enc | quote }}
  tls.crt: {{ $osTlsCrt | b64enc | quote }}
  tls.key: {{ $osTlsKey | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}