{{- if .Values.diracx.osDbs.default.useCRT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: os-certs-default
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: kubernetes.io/tls
data:
  osca.crt: {{ index .Values.diracx.osDbs.default "osca.crt" | b64enc | quote }}
  tls.crt: {{ index .Values.diracx.osDbs.default "tls.crt" | b64enc | quote }}
  tls.key: {{ index .Values.diracx.osDbs.default "tls.key" | b64enc | quote }}
{{- end }}

{{- range $dbName, $dbConfig := .Values.diracx.osDbs.dbs }}
{{- if kindIs "map" $dbConfig }}
{{- if and (hasKey $dbConfig "useCRT") ($dbConfig.useCRT) }}
{{- if and (hasKey $dbConfig "osca.crt") (hasKey $dbConfig "tls.crt") (hasKey $dbConfig "tls.key") }}
{{- $oscaCrt := index $dbConfig "osca.crt" | toString | trim }}
{{- $tlsCrt := index $dbConfig "tls.crt" | toString | trim }}
{{- $tlsKey := index $dbConfig "tls.key" | toString | trim }}
{{- if and $oscaCrt $tlsCrt $tlsKey }}
{{- $safeDbName := $dbName | lower | replace "_" "-" | replace "." "-" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "os-certs-%s" $safeDbName | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: kubernetes.io/tls
data:
  osca.crt: {{ $oscaCrt | b64enc | quote }}
  tls.crt: {{ $tlsCrt | b64enc | quote }}
  tls.key: {{ $tlsKey | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}