apiVersion: v1
kind: Secret
metadata:
  name: diracx-secrets
stringData:
{{ .Values.diracx.settings | toYaml | indent 2 }}
{{- if .Values.diracx.osDbs.GlobalIndexPrefix }}
  DIRACX_FACTORY_OS_GLOBAL_PREFIX: {{ .Values.diracx.osDbs.GlobalIndexPrefix | quote }}
{{- end }}
---
