{{- if .Values.redisTasks.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "diracx.taskRedisName" . }}
  labels:
    {{- include "diracx.labels" . | nindent 4 }}
    app.kubernetes.io/component: task-redis
spec:
  serviceName: {{ include "diracx.taskRedisName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "diracxTaskRedis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "diracxTaskRedis.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: task-redis
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "diracx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "diracx.redisTasksImage" . }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.redisTasks.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: redis
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: redis
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            {{- toYaml (.Values.redisTasks.resources | default dict) | nindent 12 }}
      volumes:
        - name: redis-data
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
