apiVersion: v2
name: diracx
description: |
  This helm chart is intended to be used in two ways:

   * Development: The ./run_demo.sh script allows the infrastructure to be ran locally with docker+kind
   * Production: TODO

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: "1.0.0-alpha.2"

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: v0.0.1a49


dependencies:

- name: opensearch
  version: 2.13.1
  repository:  https://opensearch-project.github.io/helm-charts/
  condition: opensearch.enabled

- name: elasticsearch
  version: 8.5.1
  repository:  https://helm.elastic.co
  # TODO: why was this commented?
  condition: elasticsearch.enabled

- name: dex
  version: 0.14.2
  repository: https://charts.dexidp.io/
  condition: dex.enabled

- name: minio
  version: 5.0.11
  repository: https://charts.min.io/
  condition: minio.enabled

- name: rabbitmq
  version: 12.0.10
  repository: https://charts.bitnami.com/bitnami/
  condition: rabbitmq.enabled

- name: mysql
  version: 9.11.0
  repository: https://charts.bitnami.com/bitnami/
  condition: mysql.enabled


- name: cert-manager
  version: 1.13.1
  repository: https://charts.jetstack.io
  condition: cert-manager.enabled

- name: cert-manager-issuer
  version: '*.*.*'
  condition: cert-manager-issuer.enabled

- name: opentelemetry-collector
  version: 0.68.0
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  condition: opentelemetry-collector.enabled

- name: jaeger
  version: 0.71.14
  repository: https://jaegertracing.github.io/helm-charts
  condition: jaeger.enabled

- name: grafana
  version: 6.59.4
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled

- name: prometheus
  version: 25.0.0
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus.enabled
