{{- if .Values.seaweedfs.enabled }}
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-seaweedfs
  labels:
    app: seaweedfs
    release: {{ .Release.Name }}
spec:
  selector:
    app: seaweedfs
    release: {{ .Release.Name }}
  ports:
    - name: s3
      port: {{ default 8333 .Values.seaweedfs.s3Port }}
      targetPort: {{ default 8333 .Values.seaweedfs.s3TargetPort }}
      nodePort: {{ default 32000 .Values.seaweedfs.s3NodePort }}
    - name: adminui
      port: {{ default 23646 .Values.seaweedfs.adminuiPort }}
      targetPort: {{ default 23646 .Values.seaweedfs.adminuiTargetPort }}
      nodePort: {{ default 32001 .Values.seaweedfs.adminuiNodePort }}
  type: NodePort
---
# PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-seaweedfs-data
  labels:
    app: seaweedfs
    release: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.seaweedfs.persistence.accessModes | first | quote }}
  resources:
    requests:
      storage: {{ .Values.seaweedfs.persistence.size | quote }}
  {{- if .Values.seaweedfs.persistence.storageClass }}
  storageClassName: {{ .Values.seaweedfs.persistence.storageClass | quote }}
  {{- end }}

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-seaweedfs
  labels:
    app: seaweedfs
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaweedfs
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: seaweedfs
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: seaweedfs
          image: "chrislusf/seaweedfs:4.23"
          imagePullPolicy: IfNotPresent
          args: [
            {{ .Values.seaweedfs.mode | quote }},
            "-dir",
            "/data",
            "-s3.config=/etc/seaweedfs/seaweedfs-s3.json"
          ]
          env:
            - name: S3_BUCKET
              value: {{ .Values.seaweedfs.config.bucket }}
          ports:
            - containerPort: {{ default 8333 .Values.seaweedfs.s3Port }}
              name: s3
            - containerPort: {{ default 23646 .Values.seaweedfs.adminuiPort }}
              name: adminui
          volumeMounts:
            - name: seaweedfs-data
              mountPath: /data
            - name: seaweedfs-config
              mountPath: /etc/seaweedfs/seaweedfs-s3.json
              subPath: seaweedfs-s3.json
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      volumes:
        - name: seaweedfs-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-seaweedfs-data
        - name: seaweedfs-config
          configMap:
            name: {{ .Values.seaweedfs.config.configMap.name }}
{{- end }}
