---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-diracx-code
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 2Gi
  hostPath:
    path: {{ .Values.developer.diracxSourcePath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-diracx-code
spec:
  storageClassName: ""
  volumeName: pv-diracx-code
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
