{{- $nodeDevInstall := and .Values.developer.enabled (empty .Values.developer.mountedNodeModuleToInstall | not) -}}
{{- $nodeModulePath := $nodeDevInstall | ternary (printf "%s/%s" .Values.developer.sourcePath .Values.developer.mountedNodeModuleToInstall) "" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diracx.fullname" . }}-web
  labels:
    {{- include "diracx.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "diracxWeb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/entrypoint: {{ include (print $.Template.BasePath "/web-container-entrypoint.yaml") . | sha256sum }}
      labels:
        {{- include "diracxWeb.selectorLabels" . | nindent 8 }}

    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "diracx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: container-entrypoint
          configMap:
            name: diracx-web-container-entrypoint
        {{- if $nodeDevInstall }}
        - name: diracx-web-code-mount
          persistentVolumeClaim:
            claimName: pvc-diracx-code
        - name: diracx-web-scratch-node-modules
          emptyDir:
            sizeLimit: 1Gi
        - name: diracx-web-scratch-next
          emptyDir:
            sizeLimit: 1Gi
        {{- end }}

      {{- if or $nodeDevInstall .Values.diracxWeb.nodeModuleToInstall }}
      initContainers:
        - name: build-diracx-web
          image: {{ .Values.developer.nodeImage }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}

          command: ["/bin/sh", "/entrypoint.sh"]
          volumeMounts:
            - mountPath: "/entrypoint.sh"
              subPath: "entrypoint.sh"
              name: "container-entrypoint"
            {{- if $nodeDevInstall }}
            - mountPath: "{{ .Values.developer.sourcePath }}/{{ .Values.developer.mountedNodeModuleToInstall }}"
              name: "diracx-web-code-mount"
              subPath: "{{ .Values.developer.mountedNodeModuleToInstall }}"
              readOnly: true
            - mountPath: "{{ $nodeModulePath }}/node_modules"
              name: "diracx-web-scratch-node-modules"
            - mountPath: "{{ $nodeModulePath }}/.next"
              name: "diracx-web-scratch-next"
            {{- end }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}-web
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if $nodeDevInstall }}
          image: {{ .Values.developer.nodeImage }}
          {{- else }}
          {{- if .Values.diracxWeb.nodeModuleToInstall}}
          image: {{ .Values.developer.nodeImage }}
          {{- else }}
          image: {{ .Values.global.images.web.repository }}:{{ .Values.global.images.web.tag }}
          {{- end }}
          {{- end }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.diracxWeb.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- if $nodeDevInstall }}
          command: ["npm", "run", "dev", "--prefix", "{{ $nodeModulePath }}", "--", "-p", "{{ .Values.diracxWeb.service.port }}"]
          {{- else }}
          {{ if .Values.diracxWeb.nodeModuleToInstall }}
          command: ["npm", "run", "start", "--prefix", "/diracx-web", "--", "-p", "{{ .Values.diracxWeb.service.port }}"]
          {{- end }}
          {{- end }}
          volumeMounts:
          {{- if $nodeDevInstall }}
            - mountPath: "{{ .Values.developer.sourcePath }}/{{ .Values.developer.mountedNodeModuleToInstall }}"
              name: "diracx-web-code-mount"
              subPath: "{{ .Values.developer.mountedNodeModuleToInstall }}"
              readOnly: true
            - mountPath: "{{ $nodeModulePath }}/node_modules"
              name: "diracx-web-scratch-node-modules"
            - mountPath: "{{ $nodeModulePath }}/.next"
              name: "diracx-web-scratch-next"
          {{- end }}
            - mountPath: "/entrypoint.sh"
              subPath: "entrypoint.sh"
              name: "container-entrypoint"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
